kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: 10.1.1.6:35000/${DRONE_REPO}
      registry: 10.1.1.6:35000
      insecure: true
      mirror: "https://gecwf5gs.mirror.aliyuncs.com"
      tags:
        - latest
        - ${DRONE_COMMIT}
node:
  env: act